
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 14 22:13:16 GMT-08:00 2009
//----------------------------------------------------

package tvla.language.TVP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 10;
  public static final int LCBR = 28;
  public static final int RBR = 38;
  public static final int DECOMPOSE = 42;
  public static final int PRED = 5;
  public static final int FRAME = 44;
  public static final int MINUS = 36;
  public static final int PARAM = 46;
  public static final int STAR = 17;
  public static final int CLOSE_CYCLE = 47;
  public static final int NOT = 16;
  public static final int AND = 15;
  public static final int COMBINE = 40;
  public static final int LP = 24;
  public static final int OR = 14;
  public static final int QMARK = 30;
  public static final int COMMA = 27;
  public static final int IMPLIES = 13;
  public static final int RP = 25;
  public static final int IMPLIES_T = 4;
  public static final int PLUS = 18;
  public static final int ASSIGN = 26;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int FRAME_PRE = 45;
  public static final int RCBR = 29;
  public static final int TRUE = 21;
  public static final int CLONE = 51;
  public static final int NEW = 50;
  public static final int error = 1;
  public static final int PERCENT = 32;
  public static final int EXISTS = 9;
  public static final int AUTO = 53;
  public static final int NEQ = 20;
  public static final int UNKNOWN = 23;
  public static final int ACTION = 49;
  public static final int EQ = 19;
  public static final int ARROW = 54;
  public static final int FOREACH = 33;
  public static final int CONSISTENCY_RULE = 7;
  public static final int COLON = 31;
  public static final int MESSAGE = 48;
  public static final int TITLE = 39;
  public static final int COMPOSE = 41;
  public static final int RETAIN = 52;
  public static final int LBR = 37;
  public static final int PSET = 35;
  public static final int INS_PRED = 6;
  public static final int STRING = 2;
  public static final int DECOMP_NAME = 43;
  public static final int TC = 11;
  public static final int FOCUS = 8;
  public static final int FALSE = 22;
  public static final int IFF = 12;
  public static final int SET = 34;
}

