
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Mar 08 16:13:07 IST 2004
//----------------------------------------------------

package tvla.iawp.tp.spass;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 4;
  public static final int OR = 5;
  public static final int RPAREN = 8;
  public static final int TC = 15;
  public static final int EQUAL = 14;
  public static final int NOT = 6;
  public static final int PERIOD = 13;
  public static final int TRUE = 20;
  public static final int SKOLEM_FUNCTION = 18;
  public static final int LPAREN = 7;
  public static final int LBRACKET = 9;
  public static final int RBRACKET = 10;
  public static final int STRING = 11;
  public static final int COMMA = 3;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int NULLARY_PRED = 16;
  public static final int FALSE = 19;
  public static final int error = 1;
  public static final int CLAUSE = 2;
  public static final int VAR = 12;
}

